name: 🏭 Cut Mod Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Semver Bump Type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  cut_release:
    name: "Cut Release"
    uses: open-goal/mod-bundling-tools/.github/workflows/mod-bundler.yml@v1
    with:
      semverBump: ${{ inputs.bump }}
      metadataName: "Patched"
      metadataDescription: "Jak and Daxter: The Precursor Legacy v1.1 ;)"
      metadataSupportedGames: "jak1"
      metadataAuthors: "bintendo42,barg"
      metadataTags: "speedrunning,challenge,gameplay-mod"
      metadataWebsiteUrl: "https://github.com/OpenGOAL-Mods/OG-Patched/blob/main/README.md"
      toolingRepo: "OpenGOAL-Mods/OG-Mod-Base"
      gameAssetsDir: "game/assets"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
